- name: urotaxi app
  hosts: all
  vars:
    TOMCAT_DOWNLOAD_URL: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.91/bin/apache-tomcat-9.0.91.tar.gz"
    TOMCAT_HOME_DIR: "/u01/middleware/apache-tomcat-9.0.91"
  tasks: 
    - name: install jdk11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      become: yes

    - name: create middleware dir
      file:
        path: /u01/middleware
        state: directory
        owner: ubuntu
        group: ubuntu
      become: yes

    - name: download tomcat9
      get_url:
        url: "{{ TOMCAT_DOWNLOAD_URL }}"
        dest: /u01/middleware/apache-tomcat-9.0.91.tar.gz
      become: yes

    - name: unzip tomcat
      unarchive:
        src: "/u01/middleware/apache-tomcat-9.0.91.tar.gz"
        dest: /u01/middleware
        remote_src: true
      become: yes

    - name: find jdk home
      shell: "readlink -f $(which java) | sed 's/bin.*//g'"
      register: JDK_HOME

    - name: make tomcat as a service
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      become: yes
      notify:
        - tomcatreload

    - name: install python
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes
      become: yes

    - name: install mysql client
      apt:
        name: mysql-client-8.0
        state: present
        update_cache: yes
      become: yes

    - name: copy schema
      copy:
        src: "{{ lookup('env', 'WORKSPACE') }}/src/main/db/urotaxidb.sql"
        dest: /tmp/
      become: yes

    - name: create schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /tmp/urotaxidb.sql
        login_host: "{{ lookup('env', 'DB_HOST') }}"
        login_user: "{{ lookup('env', 'UROTAXI_DB_UNAME') }}"
        login_password: "{{ lookup('env', 'UROTAXI_DB_PASSWD') }}"
      become: yes

    - name: deploy
      copy:
        src: target/urotaxi.war
        dest: "{{ TOMCAT_HOME_DIR }}/webapps/"
      notify:
        - tomcatrestart
      become: yes

  handlers:
    - name: tomcatreload
      service:
        name: tomcat
        state: reloaded
      become: yes

    - name: tomcatrestart
      service:
        name: tomcat
        state: restarted
      become: yes